name: expression-quanitify
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - stringtie==1.3.4
  - htseq==0.9.1
  - r-dplyr==0.7.4
  - r-reshape2==1.4.3
  - biopet-basecounter==0.1